import type {Snapshot,Trip} from './core';
import type {POI,Provider,Weather,Route} from './planner';
export type VerifiedRecord={placeId:string;city:string;timezone:string;area:string;setting:'urban'|'suburban';tags:Record<string,number>;currency:string;cost:number;duration:number;outdoor:boolean;meal:boolean;cuisine?:string;validFrom:string;validUntil:string;checkedAt:string;source:string;allInCap:boolean;operatorConfirmed?:boolean;availability?:{date:string;start:number;end:number}[];menu?:POI['menu'];transitCap?:number};
export const SEARCH_MASK='places.id,places.displayName,places.location,places.types,places.businessStatus,places.googleMapsUri';
export const DETAIL_MASK='id,displayName,location,businessStatus,currentOpeningHours,googleMapsUri,attributions';
export function parseCatalog(raw?:string):VerifiedRecord[]{try{const arr=JSON.parse(raw||'[]');return Array.isArray(arr)?arr.filter(r=>typeof r.placeId==='string'&&typeof r.city==='string'&&typeof r.timezone==='string'&&typeof r.area==='string'&&['urban','suburban'].includes(r.setting)&&r.tags&&typeof r.tags==='object'&&Object.values(r.tags).every(v=>typeof v==='number'&&Number.isFinite(v))&&Number.isSafeInteger(r.cost)&&r.cost>=0&&r.duration>0&&r.duration<=720&&typeof r.currency==='string'&&typeof r.outdoor==='boolean'&&typeof r.meal==='boolean'&&r.allInCap===true&&/^https:\/\//.test(r.source)&&/^\d{4}-\d{2}-\d{2}$/.test(r.validFrom)&&/^\d{4}-\d{2}-\d{2}$/.test(r.validUntil)&&Number.isFinite(Date.parse(r.checkedAt))):[];}catch{return [];}}
function pointMinute(p:any,date:string):number|null{if(!p?.date)return null;const ds=`${p.date.year}-${String(p.date.month).padStart(2,'0')}-${String(p.date.day).padStart(2,'0')}`;const diff=(Date.parse(ds)-Date.parse(date))/86400000;return Number.isFinite(diff)?diff*1440+(p.hour||0)*60+(p.minute||0):null;}
export function openingIntervals(data:any,date:string):[number,number][]{const out:[number,number][]=[];for(const p of data?.periods||[]){const a=pointMinute(p.open,date),b=pointMinute(p.close,date);if(a!==null&&b!==null&&b>a)out.push([Math.max(0,a),Math.min(1440,b)]);}return out.filter(([a,b])=>b>a);}
export function localISO(date:string,minutes:number,zone:string){let ms=Date.parse(date+'T00:00:00Z')+minutes*60000;const target=ms;for(let i=0;i<3;i++){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(ms));const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));const local=Date.parse(`${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}:${p.second}Z`);ms+=target-local;}return new Date(ms).toISOString();}
export function googleProvider(key:string,catalog:VerifiedRecord[],consume:()=>Promise<void>,transport:typeof fetch=fetch):Provider{
 let calls=0;const records=new Map(catalog.map(x=>[x.placeId,x]));const weatherCache=new Map<string,Weather[]>();
 async function call(url:string,body?:unknown,mask?:string):Promise<any>{if(++calls>40)throw Error('本輪已到達資料查詢上限，請稍後使用同輪重試。');await consume();const response=await transport(url,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-Goog-Api-Key':key,...(mask?{'X-Goog-FieldMask':mask}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error(`真實資料供應商暫時無法完成查詢（${response.status}）。`);return response.json();}
 return {async candidates(s){const eligible=catalog.filter(r=>r.city.toLowerCase()===s.trip.city.toLowerCase()&&r.validFrom<=s.trip.date&&r.validUntil>=s.trip.date&&r.currency===s.trip.currency&&Date.parse(r.checkedAt)<=Date.now());if(!eligible.length)return [];const tags=Object.entries(s.cards[6].tags).sort((a,b)=>b[1]-a[1]).map(x=>x[0]);const activity=tags.find(t=>['museum','beach','shopping','fitness','mountain','boat'].includes(t))||'attractions';const ids=new Set<string>();for(const query of [`${s.trip.city} ${activity}`,`${s.trip.city} restaurants`]){const r=await call('https://places.googleapis.com/v1/places:searchText',{textQuery:query,pageSize:10},SEARCH_MASK);for(const p of r.places||[])if(records.has(p.id))ids.add(p.id);} // Catalog IDs can supplement search, never invent a venue.
 for(const r of eligible)ids.add(r.placeId);const out:POI[]=[];for(const id of [...ids].slice(0,12)){const r=eligible.find(x=>x.placeId===id);if(!r)continue;const p=await call(`https://places.googleapis.com/v1/places/${encodeURIComponent(id)}`,undefined,DETAIL_MASK);if(!p.location||p.businessStatus!=='OPERATIONAL')continue;out.push({id,name:p.displayName?.text||id,area:r.area,setting:r.setting,lat:p.location.latitude,lng:p.location.longitude,tags:r.tags,currency:r.currency,cost:r.cost,duration:r.duration,hours:openingIntervals(p.currentOpeningHours,s.trip.date).flatMap(([a,b])=>(r.tags.paragliding||r.tags.boat)?(r.availability||[]).filter(slot=>slot.date===s.trip.date&&Number.isFinite(slot.start)&&Number.isFinite(slot.end)&&slot.end>slot.start).map(slot=>[Math.max(a,slot.start),Math.min(b,slot.end)] as [number,number]).filter(([a,b])=>b>a):[[a,b] as [number,number]]),operational:true,verified:true,outdoor:r.outdoor,meal:r.meal,cuisine:r.cuisine,source:r.source,menu:r.menu,operatorConfirmed:r.operatorConfirmed,attributions:[{provider:'Google Maps',providerUri:p.googleMapsUri},...(p.attributions||[])]});}return out;},
 async weather(p,t){const r=records.get(p.id)!;const cacheKey=`${p.id}:${t.date}`;if(weatherCache.has(cacheKey))return weatherCache.get(cacheKey)!;const start=Date.parse(localISO(t.date,t.start,r.timezone)),end=Date.parse(localISO(t.date,t.end,r.timezone));if(start<Date.now()-3600000||end>Date.now()+240*3600000)return [];let token='';const out:Weather[]=[];for(let page=0;page<4;page++){const url=new URL('https://weather.googleapis.com/v1/forecast/hours:lookup');url.search=new URLSearchParams({'location.latitude':String(p.lat),'location.longitude':String(p.lng),hours:String(Math.min(240,Math.ceil((end-Date.now())/3600000)+1)),pageSize:'240',unitsSystem:'METRIC',...(token?{pageToken:token}:{})}).toString();const data=await call(url.toString());for(const h of data.forecastHours||[]){const d=h.displayDateTime;const ds=d?`${d.year}-${String(d.month).padStart(2,'0')}-${String(d.day).padStart(2,'0')}`:'';if(ds!==t.date)continue;const rain=h.precipitation?.probability?.percent,wind=h.wind?.speed?.value;if(!Number.isFinite(rain)||!Number.isFinite(wind)||h.wind?.speed?.unit!=='KILOMETERS_PER_HOUR')continue;out.push({start:d.hours*60,end:d.hours*60+60,rain,wind,severe:!/^(CLEAR|MOSTLY_CLEAR|PARTLY_CLOUDY|MOSTLY_CLOUDY|CLOUDY|LIGHT_RAIN|RAIN|RAIN_SHOWERS|LIGHT_RAIN_SHOWERS)$/.test(h.weatherCondition?.type||'')});}token=data.nextPageToken||'';if(!token)break;}weatherCache.set(cacheKey,out);return out;},
 async route(a,b,departure,t,mode):Promise<Route|null>{const rec=records.get(a.id)!;if(mode==='TRANSIT'&&!Number.isSafeInteger(rec.transitCap))return null;const body={origin:{placeId:a.id},destination:{placeId:b.id},travelMode:mode,...(mode==='TRANSIT'?{departureTime:localISO(t.date,departure,rec.timezone)}:{})};const data=await call('https://routes.googleapis.com/directions/v2:computeRoutes',body,'routes.duration,routes.distanceMeters,routes.travelAdvisory.transitFare');const r=data.routes?.[0];if(!r||!/^\d+(\.\d+)?s$/.test(r.duration))return null;let cost=0;if(mode==='TRANSIT'){const f=r.travelAdvisory?.transitFare;if(!f||f.currencyCode!==t.currency)return null;const estimate=Math.ceil((Number(f.units||0)+Number(f.nanos||0)/1e9)*100);if(estimate>rec.transitCap!||rec.transitCap!<0)return null;cost=rec.transitCap!;}return {minutes:Math.ceil(parseFloat(r.duration)/60),cost,currency:t.currency,mode,source:'Google Maps Routes'};}};
}
