import type {Trip,Snapshot} from './core';
import type {POI,Provider,Route,Weather} from './planner';
import {byId,blend} from './spread';
export const OPEN_DATA_UNTIL='2026-10-14';
const base={region:'downtown',area:'Downtown Vancouver',setting:'urban' as const,currency:'CAD',operational:true,verified:true,outdoor:false,meal:false};
const noBooking={required:false,status:'not_required' as const,depositKind:'none' as const,deposit:0,paid:true};
const foods=[{dish:'Two Egg Veg',price:1150,start:480,end:660,tags:{nature:3,comfort:2}},{dish:'Bacon Slab',price:1150,start:480,end:660,tags:{warm:3,food:2}},{dish:'Grilled Cheese',price:1200,start:660,end:1200,tags:{warm:3,comfort:3}},{dish:'Buffalo Chicken',price:1450,start:660,end:1200,tags:{active:3,food:3}}];
export const venues=[
 {id:'library',name:'Vancouver Public Library · Central',address:'350 West Georgia Street, Vancouver, BC V6B 6B1',lat:49.279659,lng:-123.115614,source:'https://www.vpl.ca/branches/central',meal:false,tags:{study:3,quiet:3,culture:3,exhibition:1,creative:1},duration:60,cost:0,hours:[[570,1230]] as [number,number][],guard:['350 west georgia','9:30 am','8:30 pm'],foods:[]},
 {id:'nook',name:'Nook · Coal Harbour',address:'1155 Melville Street, Vancouver, BC V6E 4C4',lat:49.2873809,lng:-123.1231616,source:'https://nookrestaurants.com/coal-harbour/',menuSource:'https://order.toasttab.com/online/nook-restaurant-the-stacks-new-1133-melville-street',bookingUrl:'https://order.toasttab.com/online/nook-restaurant-the-stacks-new-1133-melville-street',meal:true,mealStyle:'takeaway',cuisine:'意式',tags:{food:3,western:3,warm:3,pair:2,comfort:2},duration:60,hours:[[690,1320]] as [number,number][],guard:['1155 melville','11:30 am','10:30 pm'],foods:[{dish:'Margherita Pizza',price:2500,start:690,end:1320,tags:{comfort:3,nature:2}},{dish:'Spaghetti Bolognese',price:2800,start:690,end:1320,tags:{warm:3,food:3}}]},
 {id:'mb-robson',name:'Meat & Bread · Robson',address:'625 Robson Street, Vancouver, BC',lat:49.2810223,lng:-123.118995,source:'https://www.meatandbread.com/robson',bookingUrl:'https://order.toasttab.com/online/meat-bread-robson-625-robson-st',meal:true,mealStyle:'takeaway',cuisine:'三文治',tags:{food:3,fastfood:3,western:2,warm:2},duration:45,hours:[[480,1200]] as [number,number][],guard:['625 robson','8am','8pm'],foods},
 {id:'mb-cambie',name:'Meat & Bread · Cambie',address:'370 Cambie Street, Vancouver, BC',lat:49.282623,lng:-123.109344,source:'https://www.meatandbread.com/cambie',bookingUrl:'https://order.toasttab.com/online/meat-bread-cambie-370-cambie-st',meal:true,mealStyle:'takeaway',cuisine:'三文治',tags:{food:3,fastfood:3,western:2,urban:2},duration:45,hours:[[480,960]] as [number,number][],guard:['370 cambie','8am','4pm'],foods},
 {id:'miku',name:'Miku Vancouver',address:'70–200 Granville Street, Vancouver, BC V6C 1S4（Howe Street 入口）',lat:49.2870647,lng:-123.112828,source:'https://mikurestaurant.com/contact/',menuSource:'https://mikurestaurant.com/menu/',bookingUrl:'https://www.opentable.ca/r/miku-restaurant-vancouver',meal:true,mealStyle:'premium',cuisine:'日式',tags:{food:3,water:3,pair:2,creative:2},duration:75,hours:[[720,1320]] as [number,number][],guard:['200 granville','10 pm'],foods:[{dish:'Salmon Oshi Sushi',price:2300,start:720,end:1320,tags:{water:3,crafted:2}},{dish:'Miku Roll',price:2500,start:720,end:1320,tags:{food:3,creative:3}},{dish:'Tofu Salad',price:2100,start:720,end:1320,tags:{nature:3,calm:2}}]},
 {id:'vag',name:'Vancouver Art Gallery',address:'750 Hornby Street, Vancouver, BC V6Z 2H7',lat:49.2828495,lng:-123.1206248,source:'https://www.vanartgallery.bc.ca/visit/',bookingUrl:'https://tickets.vanartgallery.bc.ca/',meal:false,tags:{museum:3,exhibition:3,creative:3,culture:3},duration:90,cost:4000,hours:[[600,1020]] as [number,number][],guard:['750 hornby','closed on tuesdays','$35'],foods:[]},
 {id:'harbour-green',name:'Harbour Green Park',address:'1199 W Cordova Street, Vancouver, BC',lat:49.2901767,lng:-123.1218611,source:'https://covapp.vancouver.ca/ParkFinder/FindFacilityType.aspx?InFT=41',meal:false,outdoor:true,tags:{walk:3,photography:3,water:3,skyline:2,nature:2},duration:45,cost:0,hours:[[540,1080]] as [number,number][],guard:['harbour green','1199'],foods:[]},
];
export type DataAccess={get:(key:string)=>Promise<string|null>;put:(key:string,value:string,ttl:number)=>Promise<void>;limit:(service:string)=>Promise<void>};
class RestrictedSource extends Error {}
const identity='ArcanaPrivate/3.0 (+https://arcana-day-private.hosoning.chatgpt.site)';
export function openProvider(access:DataAccess,transport:typeof fetch=fetch):Provider{
 let locations:POI[]=[];let matrix:(number|null)[][]=[];let weatherData:Weather[]|null=null;
 async function get(url:string,key:string,ttl:number){const cached=await access.get(key);if(cached)return cached;await access.limit(new URL(url).hostname);const r=await transport(url,{headers:{'User-Agent':identity,'Accept':'application/json,text/html'},signal:AbortSignal.timeout(18000)});if(r.status===403)throw new RestrictedSource();if(!r.ok)throw Error('公開資料服務暫時無法連線，請稍後用同一輪牌重試。');const value=await r.text();await access.put(key,value,ttl);return value;}
 return {walkingOnly:true,async candidates(s){const t=s.trip;if(t.city.toLowerCase()!=='vancouver'||t.currency!=='CAD')throw Error('免金鑰版目前支援 Vancouver / CAD。');if(!t.origin)throw Error('請先選擇出發位置，才能計算第一段路線。');if(t.date>OPEN_DATA_UNTIL)throw Error('這個日期超過目前已核實資料期限，請選擇 10 月 14 日或以前。');if(t.date==='2026-10-12')throw Error('10 月 12 日是假日，尚未取得商戶假日營業確認，不能排入。');const out:POI[]=[];
 for(const v of venues){if(v.id==='harbour-green')continue;try{let snapshotUsed=false;let raw='';try{raw=await get(v.source,'official:'+v.id,3600000);}catch(e){if(!(e instanceof RestrictedSource))throw e;snapshotUsed=true;} const html=raw.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/\s+/g,' ').toLowerCase();if(!snapshotUsed&&!v.guard.every(g=>html.includes(g)))continue;
 let hours=v.hours.map(x=>[...x] as [number,number]);const dow=new Date(t.date+'T12:00:00Z').getUTCDay();if(v.id==='library'){if(dow===0)hours=[[660,1080]];else if(dow===6)hours=[[600,1080]];else if(dow===5)hours=[[570,1080]];}if(v.id==='vag'){if(dow===2)continue;if(dow===5)hours=[[600,1200]];}
 let cost=v.cost||0,menu:POI['menu'];let alternatives:{dish:string;price:number;start:number;end:number}[]=[];if(v.meal){let menuRaw=raw;let menuSnapshot=snapshotUsed;if(v.menuSource)try{menuRaw=await get(v.menuSource,'menu:'+v.id,3600000);}catch(e){if(!(e instanceof RestrictedSource))throw e;menuSnapshot=true;snapshotUsed=true;}const menuText=menuRaw.replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/\s+/g,' ').toLowerCase();const card=blend(byId(s.decisions!,'dish').cards,2);const dishes=[...v.foods].filter(f=>{const at=menuText.indexOf(f.dish.toLowerCase());return (menuSnapshot||at>=0&&menuText.slice(at,at+150).includes(String(f.price/100)))&&Math.max(f.start,t.start)<Math.min(f.end,t.end)}).sort((a,b)=>Object.entries(b.tags).reduce((n,[k,v])=>n+v*(card.tags[k]||0),0)-Object.entries(a.tags).reduce((n,[k,v])=>n+v*(card.tags[k]||0),0));alternatives=dishes;const dish=dishes[0];if(!dish)continue;cost=Math.ceil(dish.price*1.35/100)*100;menu={dish:dish.dish,source:v.menuSource||v.source,validUntil:OPEN_DATA_UNTIL};hours=hours.map(([a,b])=>[Math.max(a,dish.start),Math.min(b,dish.end)]);}
 // Miku reservation/deposit availability is not publicly verifiable; keep it in the browsable catalog, not executable plans.
 if(v.id==='miku')continue;
 for(const variant of (v.meal?alternatives:[null]))out.push({...base,...v,id:v.id+(variant?':'+variant.dish:''),venueId:v.id,sourceNote:snapshotUsed?'官方資料核實於 2026-10-07；自動重查受限，僅排至 10 月 14 日。':'本次已查閱官方資料；預約名額與臨時變更以商戶為準。',tags:v.tags as unknown as Record<string,number>,hours:variant?v.hours.map(([a,b])=>[Math.max(a,variant.start),Math.min(b,variant.end)] as [number,number]):hours,cost:variant?Math.ceil(variant.price*1.35/100)*100:cost,booking:{...noBooking,url:v.bookingUrl,...(v.id==='vag'?{required:true,status:'unbooked' as const,depositKind:'included' as const,deposit:cost,deadline:t.date+'（出發前）',terms:'請於官方售票頁核對入場時段、實際票價與取消規則；付款由你處理。'}:{})},menu:variant?{dish:variant.dish,source:v.menuSource||v.source,validUntil:OPEN_DATA_UNTIL}:menu,attributions:[{provider:'OpenStreetMap contributors',providerUri:'https://www.openstreetmap.org/copyright'}]});}catch{continue;}}
 const origin={...base,id:'origin',name:t.origin.label,address:t.origin.label,lat:t.origin.lat,lng:t.origin.lng} as POI;locations=[origin,...out];if(!out.length)return [];
 const coords=locations.map(p=>`${p.lng},${p.lat}`).join(';');const raw=await get('https://routing.openstreetmap.de/routed-foot/table/v1/foot/'+coords+'?annotations=duration','foot:'+coords,86400000);const data=JSON.parse(raw);if(data.code!=='Ok'||!Array.isArray(data.durations))throw Error('未能取得步行路線。');matrix=data.durations;for(let i=0;i<locations.length;i++)if(!data.sources?.[i]||data.sources[i].distance>150){matrix[i]=matrix[i].map(()=>null);for(const row of matrix)row[i]=null;}
 return out;},
 async weather(p,t){if(weatherData)return weatherData;const raw=await get('https://api.open-meteo.com/v1/forecast?latitude=49.283&longitude=-123.12&hourly=precipitation_probability,wind_speed_10m,weather_code&timezone=America%2FVancouver&forecast_days=16','weather:vancouver',1800000);const d=JSON.parse(raw);weatherData=(d.hourly?.time||[]).flatMap((date:string,i:number)=>{const day=(Date.parse(date.slice(0,10))-Date.parse(t.date))/86400000;if(day<0||day>1)return [];const start=day*1440+Number(date.slice(11,13))*60;const rain=d.hourly.precipitation_probability[i],wind=d.hourly.wind_speed_10m[i],code=d.hourly.weather_code[i];return Number.isFinite(rain)&&Number.isFinite(wind)&&Number.isFinite(code)?[{start,end:start+60,rain,wind,severe:code>=65}]:[]});return weatherData||[];},
 async route(a,b,_departure,t,mode):Promise<Route|null>{if(mode!=='WALK')return null;const i=locations.findIndex(p=>p.id===a.id),j=locations.findIndex(p=>p.id===b.id);const seconds=matrix[i]?.[j];if(typeof seconds!=='number'||!Number.isFinite(seconds)||seconds<0)return null;return {minutes:Math.ceil(seconds/60),cost:0,currency:t.currency,mode:'WALK',source:'https://routing.openstreetmap.de/about.html',persistable:true,directionsUrl:`https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=${a.lat},${a.lng};${b.lat},${b.lng}`,instructions:'依真實步行路網估算；已另留休息時間。'};}
 };
}
