import {tagScore,type Card,type Snapshot,type Tags,type Trip} from './core';
export type Menu={dish:string;source:string;validUntil:string};
export type POI={id:string;name:string;area:string;setting:'urban'|'suburban';lat:number;lng:number;tags:Tags;currency:string;cost:number;duration:number;hours:[number,number][];operational:boolean;verified:boolean;outdoor:boolean;meal:boolean;cuisine?:string;source:string;menu?:Menu;operatorConfirmed?:boolean;attributions?:{provider:string;providerUri?:string}[]};
export type Weather={start:number;end:number;rain:number;wind:number;severe:boolean};
export type Route={minutes:number;cost:number;currency:string;mode:'WALK'|'TRANSIT';source:string};
export type Stop={poi:POI;arrival:number;departure:number;route:Route|null;reason:string};
export type Plan={stops:Stop[];total:number;score:number;diagnostics:Record<string,number>;intent:ReturnType<typeof intent>;demo:boolean};
export interface Provider {candidates(s:Snapshot):Promise<POI[]>;weather(p:POI,t:Trip):Promise<Weather[]>;route(a:POI,b:POI,departure:number,t:Trip,mode:'WALK'|'TRANSIT'):Promise<Route|null>;}
export function intent(s:Snapshot){const pace=s.cards[3];const active=(pace.tags.fast||0)+(pace.tags.active||0),slow=(pace.tags.slow||0)+(pace.tags.rest||0);const span=s.trip.end-s.trip.start;const windows=[[540,660],[660,900],[1020,1260]].filter(([a,b])=>Math.min(s.trip.end,b)-Math.max(s.trip.start,a)>=45).length;const mealCard=s.cards[4];return {pace:active>slow?'充實':slow>active?'悠閒':'平衡',dwell:active>slow?0.85:slow>active?1.25:1,target:Math.max(2,Math.min(6,Math.floor(span/(active>slow?100:slow>active?170:130)))),meals:Math.min(windows,(mealCard.tags.food||0)>=3?2:(mealCard.tags.hunger||0)>0?2:1),mode:((s.cards[11].tags.transport||0)+(s.cards[11].tags.travel||0)>2?'TRANSIT':'WALK') as 'WALK'|'TRANSIT'};}
export function rejection(p:POI,arrival:number,departure:number,total:number,t:Trip,w:Weather[]):string|null{if(!p.operational)return 'closed';if(!p.verified||!Number.isFinite(p.lat)||!Number.isFinite(p.lng)||!Number.isSafeInteger(p.cost)||p.cost<0||!Number.isFinite(p.duration)||p.duration<=0)return 'unverified';if(p.currency!==t.currency)return 'currency';if(total>t.budget)return 'budget';if(departure>t.end)return 'time';if(!p.hours.some(([a,b])=>a<=arrival&&b>=departure))return 'hours';if(p.meal&&![[540,660],[660,900],[1020,1260]].some(([a,b])=>arrival>=a&&departure<=b))return 'meal_window';if((p.tags.paragliding||p.tags.boat)&&!p.operatorConfirmed)return 'operator';if(p.outdoor){const cover=w.filter(h=>h.end>arrival&&h.start<departure).sort((a,b)=>a.start-b.start);let until=arrival;for(const h of cover){if(h.start>until)return 'weather_missing';if(h.severe||h.rain>(p.tags.paragliding?10:p.tags.mountain?40:65)||h.wind>(p.tags.paragliding?20:p.tags.boat?30:45))return 'weather';until=Math.max(until,h.end);}if(until<departure)return 'weather_missing';}return null;}
function score(p:POI,s:Snapshot,index:number){const activity=s.cards[6+(index%4)],region=s.cards[1],setting=s.cards[2],seq=s.cards[10];let v=tagScore(p.tags,activity)*2+tagScore(p.tags,region);v+=(p.setting==='urban'?(setting.tags.urban||0):(setting.tags.nature||0))*4;if(p.meal)v+=tagScore(p.tags,s.cards[5])*2;v+=index===0?(seq.tags.active||0)*(p.tags.active||0):(seq.tags.rest||0)*(p.tags.calm||0);return v;}
export async function optimize(s:Snapshot,provider:Provider):Promise<Plan>{const t=s.trip,goal=intent(s),diagnostics:Record<string,number>={};const reject=(k:string)=>{diagnostics[k]=(diagnostics[k]||0)+1;};const ranked=(await provider.candidates(s)).sort((a,b)=>score(b,s,0)-score(a,s,0)||a.id.localeCompare(b.id));const all=[...ranked.filter(p=>!p.meal).slice(0,8),...ranked.filter(p=>p.meal).slice(0,4)];if(!all.length)return {stops:[],total:0,score:0,diagnostics:{no_verified_candidates:1},intent:goal,demo:t.mode==='demo'};
 const weather=new Map<string,Weather[]>();for(const p of all)if(p.outdoor)weather.set(p.id,await provider.weather(p,t));
 type State={stops:Stop[];total:number;score:number;end:number;meals:number;mealSlots:number[]};let states:State[]=[{stops:[],total:0,score:0,end:t.start,meals:0,mealSlots:[]}];const completed:State[]=[];const routes=new Map<string,Route|null>();let routeLookups=0;
 for(let depth=0;depth<goal.target;depth++){const next:State[]=[];for(const st of states){for(const p of all){if(st.stops.some(x=>x.poi.id===p.id)||p.meal&&st.meals>=goal.meals)continue;const last=st.stops.at(-1);let route:Route|null=null;if(last){const key=`${last.poi.id}:${p.id}:${st.end}:${goal.mode}`;if(routes.has(key))route=routes.get(key)!;else{if(routeLookups>=(t.mode==='demo'?2000:20)){reject('route_call_limit');continue;}routeLookups++;route=await provider.route(last.poi,p,st.end,t,goal.mode);routes.set(key,route);}if(!route||!Number.isFinite(route.minutes)||route.minutes<0||!Number.isSafeInteger(route.cost)||route.cost<0||route.currency!==t.currency){reject('route');continue;}}
 const reach=st.end+(route?.minutes||0)+(last?10:0),duration=Math.ceil(p.duration*(p.meal?1:goal.dwell));let arrival=reach; // Waiting for an opening is valid; it consumes the time budget.
 const intervals=p.hours.map(([a,b])=>[Math.max(a,reach),b]).filter(([a,b])=>b-a>=duration);if(p.meal){const mealIntervals:number[][]=[];for(const [a,b] of intervals)for(const [c,d] of [[540,660],[660,900],[1020,1260]].filter((_,i)=>!st.mealSlots.includes(i)))if(Math.min(b,d)-Math.max(a,c)>=duration)mealIntervals.push([Math.max(a,c),Math.min(b,d)]);arrival=mealIntervals.sort((a,b)=>a[0]-b[0])[0]?.[0]??reach;}else arrival=intervals.sort((a,b)=>a[0]-b[0])[0]?.[0]??reach;
 const departure=arrival+duration,total=st.total+p.cost+(route?.cost||0);const reason=rejection(p,arrival,departure,total,t,weather.get(p.id)||[]);if(reason){reject(reason);continue;}const mealSlot=p.meal?[[540,660],[660,900],[1020,1260]].findIndex(([a,b])=>arrival>=a&&departure<=b):-1;if(p.meal&&st.mealSlots.includes(mealSlot)){reject('meal_window');continue;}const card:Card=p.meal?s.cards[5]:s.cards[6+depth%4];const stop:Stop={poi:{...p,menu:p.menu&&p.menu.validUntil>=t.date&&/^https:\/\//.test(p.menu.source)?p.menu:undefined},arrival,departure,route,reason:`${card.name} · ${card.meaning}`};next.push({stops:[...st.stops,stop],total,score:st.score+score(p,s,depth)+30-(arrival-reach)*0.15-(route?.minutes||0)*0.25,end:departure,meals:st.meals+Number(p.meal),mealSlots:p.meal?[...st.mealSlots,mealSlot]:st.mealSlots});}}
 next.sort((a,b)=>b.score-a.score||a.total-b.total||a.stops.map(x=>x.poi.id).join().localeCompare(b.stops.map(x=>x.poi.id).join()));states=next.slice(0,6);completed.push(...states.filter(x=>x.meals===goal.meals&&x.stops.length>=2));if(!states.length)break;}
 const best=completed.sort((a,b)=>b.stops.length-a.stops.length||b.score-a.score||a.total-b.total)[0];if(!best)reject('no_complete_plan');return {stops:best?.stops||[],total:best?.total||0,score:best?.score||0,diagnostics,intent:goal,demo:t.mode==='demo'};}
