import {tagScore,type Snapshot,type Tags,type Trip} from './core';
import {byId,selected,detailDecisions,mealWindows,activities,type Decision} from './spread';
export type Menu={dish:string;source:string;validUntil:string};
export type Booking={required:boolean;url?:string;status:'not_required'|'unbooked'|'confirmed';depositKind:'none'|'included'|'additional'|'unknown';deposit:number;deadline?:string;terms?:string;checkedAt?:string;reference?:string;paid?:boolean};
export type POI={id:string;venueId?:string;sourceNote?:string;name:string;address:string;area:string;region?:string;setting:'urban'|'suburban';lat:number;lng:number;tags:Tags;currency:string;cost:number;duration:number;hours:[number,number][];operational:boolean;verified:boolean;outdoor:boolean;meal:boolean;mealStyle?:string;cuisine?:string;source:string;booking:Booking;menu?:Menu;operatorConfirmed?:boolean;attributions?:{provider:string;providerUri?:string}[]};
export type Weather={start:number;end:number;rain:number;wind:number;severe:boolean};
export type Route={minutes:number;cost:number;currency:string;mode:'WALK'|'TRANSIT';source:string;directionsUrl?:string;instructions?:string;persistable?:boolean};
export type Stop={poi:POI;arrival:number;departure:number;leavePrevious:number;waiting:number;route:Route|null;reason:string;activity:string};
export type Plan={stops:Stop[];total:number;score:number;diagnostics:Record<string,number>;intent:ReturnType<typeof intent>;demo:boolean;decisions:Decision[];adjustments:string[];gift:{enabled:boolean;description:string;reserve:number;handled:boolean;palette?:string};generatedAt:string;trip:Trip;returnRoute?:Route;returnAt?:number};
export interface Provider {candidates(s:Snapshot):Promise<POI[]>;walkingOnly?:boolean;weather(p:POI,t:Trip):Promise<Weather[]>;route(a:POI,b:POI,departure:number,t:Trip,mode:'WALK'|'TRANSIT'):Promise<Route|null>;}
export function intent(s:Snapshot){const ds=s.decisions||detailDecisions(s.cards,s.trip);const duration=selected(ds,'duration'),available=s.trip.end-s.trip.start;const durationCap=duration==='short'?Math.min(110,available):duration==='half'?Math.min(360,available):available;const requestedMeals=Number(selected(ds,'mealCount'));const meals=Math.max(1,Math.min(requestedMeals,Math.floor((durationCap-45)/150)+1));const pace=selected(ds,'pace');return {pace:pace==='slow'?'悠閒':pace==='active'?'充實':'平衡',dwell:pace==='slow'?1.2:pace==='active'?0.9:1,target:Math.min(6,Math.max(meals+(selected(ds,'firstMeal')==='no'?1:0),durationCap<120?1:Math.floor(durationCap/90))),meals,requestedMeals,mode:selected(ds,'transport') as 'WALK'|'TRANSIT',buffer:Number(selected(ds,'rest')),end:s.trip.start+durationCap,firstMeal:selected(ds,'firstMeal')==='yes',surprise:selected(ds,'surprise')==='yes',duration};}
export function rejection(p:POI,arrival:number,departure:number,total:number,t:Trip,w:Weather[]):string|null{if(!p.operational)return 'closed';if(!p.verified||!p.name||!p.address||!Number.isFinite(p.lat)||!Number.isFinite(p.lng)||!Number.isSafeInteger(p.cost)||p.cost<0||!Number.isFinite(p.duration)||p.duration<=0)return 'unverified';if(p.currency!==t.currency)return 'currency';if(total>t.budget)return 'budget';if(departure>t.end)return 'time';if(!p.hours.some(([a,b])=>a<=arrival&&b>=departure))return 'hours';const b=p.booking;if(!b||!Number.isSafeInteger(b.deposit)||b.deposit<0)return 'booking';if(t.mode==='live'&&(b.required&&!/^https:\/\//.test(b.url||'')||b.depositKind==='unknown'||b.deposit>0&&!b.deadline))return 'booking';if((p.tags.paragliding||p.tags.boat)&&!p.operatorConfirmed)return 'operator';if(p.outdoor){const cover=w.filter(h=>h.end>arrival&&h.start<departure).sort((a,b)=>a.start-b.start);let until=arrival;for(const h of cover){if(h.start>until)return 'weather_missing';if(h.severe||h.rain>(p.tags.paragliding?10:p.tags.mountain?40:65)||h.wind>(p.tags.paragliding?20:p.tags.boat?30:45))return 'weather';until=Math.max(until,h.end);}if(until<departure)return 'weather_missing';}return null;}
export function activityFor(ds:Decision[],index:number){const a=byId(ds,`activity${index+1}`);return a.ranking[selected(ds,`confirm${index+1}`)==='yes'?0:1];}
function score(p:POI,s:Snapshot,ds:Decision[],index:number,mealIndex:number){const a=byId(ds,`activity${index+1}`).card,region=byId(ds,`region${index+1}`);let v=tagScore(p.tags,a)+(p.region===region.selected?35:0);if(!p.meal){v+=(p.tags[activityFor(ds,index)]||0)*12;if(selected(ds,'photo')==='yes')v+=(p.tags.photography||0)*3;if(selected(ds,'shopping')==='yes')v+=(p.tags.shopping||0)*4;if(selected(ds,'rainBackup')==='yes'&&!p.outdoor)v+=5;}else{const c=byId(ds,mealIndex===0?'cuisine':`meal${Math.min(4,mealIndex+1)}Cuisine`);v+=tagScore(p.tags,c.card)+(p.tags[c.selected]||0)*14;if(!mealIndex){v+=tagScore(p.tags,byId(ds,'dish').card);if(p.mealStyle===selected(ds,'mealStyle'))v+=60;}}if(index===intent(s).target-1)v+=tagScore(p.tags,byId(ds,'finish').card)*2;v+=tagScore(p.tags,byId(ds,'comfort').card);return v;}
export async function optimize(s:Snapshot,provider:Provider):Promise<Plan>{const ds=s.decisions||detailDecisions(s.cards,s.trip),goal=intent(s),t={...s.trip,end:goal.end},diagnostics:Record<string,number>={},adjustments:string[]=[];const reject=(k:string)=>{diagnostics[k]=(diagnostics[k]||0)+1;};const giftEnabled=selected(ds,'gift')==='yes',giftReserve=0;const base={stops:[] as Stop[],total:giftReserve,score:0,diagnostics,intent:goal,demo:t.mode==='demo',decisions:ds,adjustments,gift:{enabled:giftEnabled,description:byId(ds,'giftStyle').label,reserve:giftReserve,handled:true,palette:selected(ds,'giftBudget')},generatedAt:new Date().toISOString(),trip:s.trip};if(goal.meals!==goal.requestedMeals)adjustments.push(`可用時長容納 ${goal.meals} 餐；原牌偏向 ${goal.requestedMeals} 餐，已使用同輪牌依時長收窄。`);
 if(provider.walkingOnly&&goal.mode!=='WALK'){goal.mode='WALK';adjustments.push('這版使用可核實的步行路線，未接公共交通班次。');}
 const origin=s.trip.origin?{id:'origin',name:s.trip.origin.label,address:s.trip.origin.label,lat:s.trip.origin.lat,lng:s.trip.origin.lng} as POI:null;
 const ranked=[...(await provider.candidates(s))].sort((a,b)=>score(b,s,ds,0,0)-score(a,s,ds,0,0)||a.id.localeCompare(b.id));const all=[...ranked.filter(p=>!p.meal).slice(0,8),...ranked.filter(p=>p.meal).slice(0,8)];if(!all.length){reject('no_verified_candidates');return base;}const weather=new Map<string,Weather[]>();for(const p of all)if(p.outdoor||provider.walkingOnly)weather.set(p.id,await provider.weather(p,t));
 type State={stops:Stop[];total:number;score:number;end:number;meals:number;lastMeal:number};let states:State[]=[{stops:[],total:giftReserve,score:0,end:t.start,meals:0,lastMeal:-10000}],completed:State[]=[];const routes=new Map<string,Route|null>();let routeLookups=0;
 for(let depth=0;depth<goal.target;depth++){const next:State[]=[];for(const st of states){const candidates=[...all].sort((a,b)=>score(b,s,ds,depth,st.meals)-score(a,s,ds,depth,st.meals));for(const p of candidates){if(st.stops.some(x=>(x.poi.venueId||x.poi.id)===(p.venueId||p.id))||p.meal&&st.meals>=goal.meals){reject('used_or_meal_limit');continue;}if(depth===0&&goal.target>1&&p.meal!==goal.firstMeal){reject('first_meal_order');continue;}if(!p.meal&&goal.target-depth<=goal.meals-st.meals){reject('meal_capacity');continue;}if(!p.meal&&selected(ds,`confirm${depth+1}`)==='no'&&p.tags[byId(ds,`activity${depth+1}`).ranking[0]]){reject('activity_declined');continue;}const last=st.stops.at(-1);const from=last?.poi||origin;let route:Route|null=null;if(from){const key=`${from.id}:${p.id}:${st.end}:${goal.mode}`;if(routes.has(key))route=routes.get(key)!;else{if(routeLookups>=(provider.walkingOnly||t.mode==='demo'?4000:20)){reject('route_call_limit');continue;}routeLookups++;route=await provider.route(from,p,st.end,t,goal.mode);routes.set(key,route);}if(!route||!Number.isFinite(route.minutes)||route.minutes<0||!Number.isSafeInteger(route.cost)||route.cost<0||route.currency!==t.currency){reject('route');continue;}}
 const reach=st.end+(route?.minutes||0)+(last?goal.buffer:0),duration=Math.ceil(p.duration*(p.meal?1:goal.dwell))+(selected(ds,'photo')==='yes'&&p.tags.photography?10:0);let ranges=p.hours.map(([a,b])=>[Math.max(a,reach,p.meal?st.lastMeal+150:0),Math.min(b,t.end)]);if(p.meal&&st.meals===0){const meal=mealWindows(selected(ds,'mealTime'),t);ranges=ranges.flatMap(([a,b])=>meal.map(([c,d])=>[Math.max(a,c),Math.min(b,d)]));}ranges=ranges.filter(([a,b])=>b-a>=duration).sort((a,b)=>a[0]-b[0]);if(!ranges.length){reject(p.meal?'meal_window':'hours');continue;}let arrival=ranges[0][0];if(goal.duration==='overnight'&&depth===goal.target-1)arrival=Math.max(arrival,1440);const departure=arrival+duration;const extra=p.booking.depositKind==='additional'?p.booking.deposit:0;const total=st.total+p.cost+extra+(route?.cost||0);if(provider.walkingOnly&&route){const coverage=weather.get(p.id)||[];const travelCheck=rejection({...p,outdoor:true,hours:[[st.end,arrival]],duration:1,cost:0},st.end,arrival,total,t,coverage);if(travelCheck){reject(travelCheck);continue;}}const reason=rejection(p,arrival,departure,total,t,weather.get(p.id)||[]);if(reason){reject(reason);continue;}const card=byId(ds,p.meal?(st.meals===0?'cuisine':`meal${st.meals+1}Cuisine`):`activity${depth+1}`).card;const actualActivity=p.meal?(p.cuisine||'餐飲'):activities.filter(a=>p.tags[a.id]).map(a=>a.label).join('、')||'活動';const stop:Stop={poi:{...p,menu:p.menu&&p.menu.validUntil>=t.date&&/^https:\/\//.test(p.menu.source)?p.menu:undefined},arrival,departure,leavePrevious:Math.max(st.end,arrival-(route?.minutes||0)-goal.buffer),waiting:arrival-reach,route,reason:`${card.name} · ${card.meaning}`,activity:actualActivity};next.push({stops:[...st.stops,stop],total,score:st.score+score(p,s,ds,depth,st.meals)+30-(arrival-reach)*0.1-(route?.minutes||0)*0.25,end:departure,meals:st.meals+Number(p.meal),lastMeal:p.meal?arrival:st.lastMeal});}}
 next.sort((a,b)=>b.score-a.score||a.total-b.total||a.stops.map(x=>x.poi.id).join().localeCompare(b.stops.map(x=>x.poi.id).join()));states=[];for(let n=0;n<=goal.meals;n++)states.push(...next.filter(x=>x.meals===n).slice(0,4));completed.push(...states.filter(x=>x.meals===goal.meals&&x.stops.length>=(goal.target===1?1:2)&&(goal.duration!=='overnight'||x.end>1440)));if(!states.length)break;}
 let best:State|undefined;let returnRoute:Route|undefined;for(const candidate of completed.sort((a,b)=>b.stops.length-a.stops.length||b.score-a.score||a.total-b.total)){const back=origin?await provider.route(candidate.stops.at(-1)!.poi,origin,candidate.end,t,goal.mode):null;if(origin&&(!back||candidate.end+back.minutes>t.end||candidate.total+back.cost>t.budget)){reject('return_route');continue;}best=candidate;returnRoute=back||undefined;break;}if(!best){reject('no_complete_plan');return base;}const elapsed=best.end-t.start;if((goal.duration==='half'&&elapsed<240)||(goal.duration==='full'&&elapsed<360))adjustments.push(`牌面預留較長時段；核實後可執行內容共 ${Math.floor(elapsed/60)} 小時 ${elapsed%60} 分鐘，餘下時間自由休息，不虛構活動填滿。`);const first=best.stops.find(x=>x.poi.meal)!;if(first.poi.mealStyle!==selected(ds,'mealStyle'))adjustments.push(`第一餐首選「${byId(ds,'mealStyle').label}」無可行組合，改用已核實的「${({home:'家裡做／翻熱',takeaway:'自己買／外賣',regular:'普通餐廳',premium:'高級餐廳'} as Record<string,string>)[first.poi.mealStyle||'regular']}」。`);best.stops.forEach((x,i)=>{if(x.poi.region!==selected(ds,`region${i+1}`))adjustments.push(`第 ${i+1} 站：牌面地區偏好與可行性取捨後選用 ${x.poi.area}。`);if(!x.poi.meal&&!x.poi.tags[activityFor(ds,i)])adjustments.push(`第 ${i+1} 站：首選活動受現實限制，使用同輪牌的下一個可行候選「${x.activity}」。`);});if(best.stops[0].poi.meal!==goal.firstMeal)adjustments.push('短行程只有一餐，首站必須用餐。');return {...base,stops:best.stops,total:best.total+(returnRoute?.cost||0),score:best.score,returnRoute,returnAt:best.end+(returnRoute?.minutes||0)};}
