import {env} from 'cloudflare:workers';
import {draw,commitment,publicRound,type Snapshot,type Trip} from './core';
export function database(){if(!env.DB)throw Error('儲存服務尚未就緒，請稍後再試。');return env.DB;}
export async function consume(bucket:string,max:number){const row=await database().prepare('INSERT INTO usage (bucket,count) VALUES (?,1) ON CONFLICT(bucket) DO UPDATE SET count=count+1 WHERE count < ? RETURNING count').bind(bucket,max).first();if(!row)throw Error('已到達本時段查詢上限，請稍後再試。');}
export async function createRound(session:string,trip:Trip){await consume(`draw:${session}:${Math.floor(Date.now()/3600000)}`,120);const snapshot=draw(trip),salt=crypto.randomUUID(),id=crypto.randomUUID(),hash=await commitment(snapshot,salt),now=Date.now(),expires=Math.max(now+86400000,Math.min(Date.parse(trip.date)+3*86400000,now+90*86400000));await database().batch([database().prepare('UPDATE rounds SET status=? WHERE session_id=? AND status=?').bind('void',session,'pending'),database().prepare('INSERT INTO rounds (id,session_id,snapshot,salt,commitment,status,created_at,expires_at) VALUES (?,?,?,?,?,?,?,?)').bind(id,session,JSON.stringify(snapshot),salt,hash,'pending',now,expires),database().prepare('DELETE FROM rounds WHERE expires_at < ?').bind(now)]);return publicRound(id,snapshot,hash,expires);}
export type Row={id:string;session_id:string;snapshot:string;salt:string;commitment:string;status:string;expires_at:number;answer:string|null;planning_until:number};
export async function readRound(id:string,session:string){const r=await database().prepare('SELECT * FROM rounds WHERE id=? AND session_id=? AND expires_at>?').bind(id,session,Date.now()).first<Row>();if(!r)throw Error('此輪已過期或不屬於這個瀏覽器，請重新開始。');return r;}
export async function reveal(id:string,session:string,answer:string){const r=await readRound(id,session);const s=JSON.parse(r.snapshot) as Snapshot;if(r.status!=='pending')return {row:r,snapshot:s,consumed:false};const status=answer==='yes'?'passed':'void';const updated=await database().prepare('UPDATE rounds SET status=?,answer=? WHERE id=? AND session_id=? AND status=? RETURNING *').bind(status,answer,id,session,'pending').first<Row>();return {row:updated||await readRound(id,session),snapshot:s,consumed:!!updated};}
export async function lease(id:string){return database().prepare('UPDATE rounds SET planning_until=? WHERE id=? AND status=? AND planning_until < ? RETURNING id').bind(Date.now()+120000,id,'passed',Date.now()).first();}
export async function release(id:string){await database().prepare('UPDATE rounds SET planning_until=0 WHERE id=?').bind(id).run();}

export async function savePlan(id:string,session:string,plan:import('./planner').Plan,expires:number){const own=structuredClone(plan);if(!own.demo)for(const stop of own.stops){stop.poi.lat=0;stop.poi.lng=0;stop.poi.hours=[];stop.poi.attributions=undefined;if(stop.route&&!stop.route.persistable)throw Error('路線未有可保存的核實時間上限。');}await database().prepare('INSERT INTO itineraries (round_id,session_id,plan,created_at,expires_at) VALUES (?,?,?,?,?) ON CONFLICT(round_id) DO NOTHING').bind(id,session,JSON.stringify(own),Date.now(),expires).run();}
export type Saved={round_id:string;session_id:string;plan:string;revealed:number;expires_at:number};
export async function savedPlan(id:string,session:string){return database().prepare('SELECT * FROM itineraries WHERE round_id=? AND session_id=? AND expires_at>?').bind(id,session,Date.now()).first<Saved>();}
export async function latestRound(session:string){return database().prepare('SELECT * FROM rounds WHERE session_id=? AND status IN (?,?) AND expires_at>? ORDER BY created_at DESC LIMIT 1').bind(session,'pending','passed',Date.now()).first<Row>();}
