import {makeKeepsake} from './keepsake';
import type {Plan,Stop} from './planner';
import {localISO} from './google';
export const timeLabel=(m:number)=>`${m>=1440?'翌日 ':''}${String(Math.floor(m%1440/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
export function releaseTime(plan:Plan,stop:Stop){return Date.parse(localISO(plan.trip.date,plan.stops[0]===stop?Math.min(stop.arrival-120,stop.leavePrevious-15):Math.max(plan.trip.start-30,stop.arrival-(stop.route?.minutes||0)-plan.intent.buffer-15),plan.trip.timezone||'America/Vancouver'));}
export function reminder(plan:Plan,index:number){const s=plan.stops[index];return `${timeLabel(s.arrival)} 到达 ${s.poi.name}，${s.poi.address}。${s.route?`${s.route.mode==='WALK'?'步行':'公共交通'}约 ${s.route.minutes} 分钟；${timeLabel(s.leavePrevious)} 出发。`:s.travelAllowance?`出门预留 ${s.travelAllowance.label}（抽牌安排）；${timeLabel(s.leavePrevious)} 出门。`:''}安排：${s.activity}。${s.poi.booking.required?'请先确认预约完成。':''}`;}
export function redacted(plan:Plan,now=Date.now()){const due=plan.stops.filter(s=>releaseTime(plan,s)<=now);const next=plan.stops.find(s=>releaseTime(plan,s)>now);return {surprise:true,serverNow:now,total:plan.total,currency:plan.trip.currency,trip:plan.trip,stopCount:plan.stops.length,meals:plan.intent.meals,demo:plan.demo,revealed:due.map(s=>({...s,hint:reminder(plan,plan.stops.indexOf(s))})),nextRelease:next?releaseTime(plan,next):null,ready:plan.stops.every(s=>!s.poi.booking.required||s.poi.booking.status==='confirmed')&&plan.stops.every(s=>!s.poi.booking.deposit||s.poi.booking.paid)&&plan.gift.handled,payments:plan.stops.filter(s=>s.poi.booking.deposit>0&&!s.poi.booking.paid).map(s=>({id:s.poi.id,amount:s.poi.booking.deposit,deadline:s.poi.booking.deadline,kind:s.poi.booking.depositKind,message:'此项需要你处理付款；亲自开启商户付款页可能会揭晓惊喜。'})),bookingCount:plan.stops.filter(s=>s.poi.booking.required&&s.poi.booking.status!=='confirmed').length,bookingTasks:plan.stops.filter(s=>s.poi.booking.required&&s.poi.booking.status!=='confirmed').map(s=>({id:s.poi.id,label:'第 '+(plan.stops.indexOf(s)+1)+' 站预约'})),giftPending:!plan.gift.handled,complete:!next,keepsake:!next?makeKeepsake(plan):null};}
export function organizerMarkdown(plan:Plan){return `# 预约资料\n\n他：${plan.trip.characterName}\n你／预约姓名：${plan.trip.userName}\n姓名：${plan.trip.userName}；实际预约人数：1 人。\n日期：${plan.trip.date}；时区：${plan.trip.timezone}。\n\n只需协助预约。提示与纪念卡由网站处理，不需代买礼物或传送提示。需要付款时通知本人；没有付款授权。\n\n`+plan.stops.filter(s=>s.poi.booking.url).map(s=>`## ${s.poi.name}\n时间：${timeLabel(s.arrival)}–${timeLabel(s.departure)}\n地址：${s.poi.address}\n预约／订餐页：${s.poi.booking.url}\n是否需预约：${s.poi.booking.required?'是':'无需预约，可自行提前订餐'}\n订金预留：${plan.trip.currency} ${(s.poi.booking.deposit/100).toFixed(2)}\n期限：${s.poi.booking.deadline||'无'}\n备注：${s.poi.booking.terms||'依商户页面确认；不要擅自购买。'}\n`).join('\n');}
const escapeICS=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');
export function calendarICS(plan:Plan,url:string){const stamp=(n:number)=>new Date(n).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');const rows=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Arcana//Private itinerary//ZH','CALSCALE:GREGORIAN'];plan.stops.forEach((s,i)=>{const at=releaseTime(plan,s);rows.push('BEGIN:VEVENT',`UID:arcana-${plan.trip.date}-${s.poi.id}-${i}`,`DTSTAMP:${stamp(Date.now())}`,`DTSTART:${stamp(at)}`,`DTEND:${stamp(at+60000)}`,`SUMMARY:Arcana · 第 ${i+1} 个约会提示`, `DESCRIPTION:${escapeICS('打开私有行程查看此刻提示。未来站点保持隐藏。 '+url)}`,'BEGIN:VALARM','TRIGGER:PT0M','ACTION:DISPLAY','DESCRIPTION:打开 Arcana 查看提示','END:VALARM','END:VEVENT');});return rows.concat('END:VCALENDAR').map(line=>{let out='',part='';for(const ch of line){if(new TextEncoder().encode(part+ch).length>70){out+=part+'\r\n ';part='';}part+=ch;}return out+part;}).join('\r\n');}
