import type {Plan,Stop} from './planner';
import {localISO} from './google';
export const timeLabel=(m:number)=>`${m>=1440?'翌日 ':''}${String(Math.floor(m%1440/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
export function releaseTime(plan:Plan,stop:Stop){return Date.parse(localISO(plan.trip.date,plan.stops[0]===stop?stop.arrival-120:Math.max(plan.trip.start-30,stop.arrival-(stop.route?.minutes||0)-plan.intent.buffer-15),plan.trip.timezone||'America/Vancouver'));}
export function reminder(plan:Plan,index:number){const s=plan.stops[index];return `${timeLabel(s.arrival)} 到達 ${s.poi.name}，${s.poi.address}。${s.route?`${s.route.mode==='WALK'?'步行':'公共交通'}約 ${s.route.minutes} 分鐘；${timeLabel(s.leavePrevious)} 從上一站出發。`:'請自行前往第一站，提前 15 分鐘到達。'}安排：${s.activity}。${s.poi.booking.required?'請先確認預約完成。':''}`;}
export function redacted(plan:Plan,now=Date.now()){const due=plan.stops.filter(s=>releaseTime(plan,s)<=now);const next=plan.stops.find(s=>releaseTime(plan,s)>now);return {surprise:true,serverNow:now,total:plan.total,currency:plan.trip.currency,trip:plan.trip,stopCount:plan.stops.length,meals:plan.intent.meals,demo:plan.demo,revealed:due.map(s=>({...s,hint:reminder(plan,plan.stops.indexOf(s))})),nextRelease:next?releaseTime(plan,next):null,ready:plan.stops.every(s=>!s.poi.booking.required||s.poi.booking.status==='confirmed')&&plan.stops.every(s=>!s.poi.booking.deposit||s.poi.booking.paid)&&plan.gift.handled,payments:plan.stops.filter(s=>s.poi.booking.deposit>0&&!s.poi.booking.paid).map(s=>({id:s.poi.id,amount:s.poi.booking.deposit,deadline:s.poi.booking.deadline,kind:s.poi.booking.depositKind,message:'此項需要你處理付款；親自開啟商戶付款頁可能會揭曉驚喜。'})),bookingCount:plan.stops.filter(s=>s.poi.booking.required&&s.poi.booking.status!=='confirmed').length,bookingTasks:plan.stops.filter(s=>s.poi.booking.required&&s.poi.booking.status!=='confirmed').map(s=>({id:s.poi.id,label:'第 '+(plan.stops.indexOf(s)+1)+' 站預約'})),giftPending:!plan.gift.handled,complete:!next};}
export function organizerMarkdown(plan:Plan){const fmt=(n:number)=>`${plan.trip.currency} ${(n/100).toFixed(2)}`;return `# Arcana 執行方資料包 — 包含完整劇透\n\n${plan.demo?'注意：全部場地、地址、路線及付款資料為虛構示範，不能實際預約。\n\n':''}日期：${plan.trip.date}；時區：${plan.trip.timezone}；1 人。\n總預算：${fmt(plan.trip.budget)}；計劃上限（含禮物預留）：${fmt(plan.total)}。\n\n請由朋友或使用者自行選擇的 AI 協助預約。這個檔案不等於已發送、已預約或已付款。不要一次把行程給參加者；依下列發送時間傳送提示。需要訂金時先通知本人處理，不自行承諾付款。沒有指定收件人或通訊渠道時，先確認如何聯絡參加者。\n\n`+plan.stops.map((s,i)=>`## ${i+1}. ${timeLabel(s.arrival)}–${timeLabel(s.departure)} ${s.poi.name}\n\n地址：${s.poi.address}\n地區：${s.poi.area}\n安排：${s.activity}\n${s.route?`交通：${s.route.mode==='WALK'?'步行':'公共交通'}，${s.route.minutes} 分鐘，${fmt(s.route.cost)}；出發 ${timeLabel(s.leavePrevious)}。路線：${s.route.directionsUrl||'示範路線'}\n`:'首站集合：參加者自行前往，提前 15 分鐘到達。\n'}等待／休息：${s.waiting+plan.intent.buffer} 分鐘\n費用上限：${fmt(s.poi.cost)}\n預約：${s.poi.booking.required?'需要':'不需要'}；狀態：${s.poi.booking.status}\n預訂頁：${s.poi.booking.url||'無需預約'}\n訂金：${fmt(s.poi.booking.deposit)}（${s.poi.booking.depositKind}）；期限：${s.poi.booking.deadline||'無'}；付款：${s.poi.booking.paid?'已處理':'未處理'}\n取消規則：${s.poi.booking.terms||'不適用／請向營運方確認'}\n來源：${s.poi.source}\n${s.poi.menu?`可靠菜單：${s.poi.menu.dish} — ${s.poi.menu.source}\n`:''}\n### 按時發送提示\n發送時間：${new Date(releaseTime(plan,s)).toISOString()}（UTC；換算 ${plan.trip.timezone}）\n${reminder(plan,i)}\n`).join('\n')+`\n## 禮物\n${plan.gift.enabled?`${plan.gift.description}。這只是象徵方向，尚未購買。上限 ${fmt(plan.gift.reserve)}；請確認實物／免費心意、安排交付，不可超支。`:'本輪沒有安排禮物。'}\n\n## 完成清單\n- 核對所有地址、時段、取消規則、交通及天氣。\n- 預訂每一項需要預約的行程；記錄確認編號。\n- 訂金由本人處理，確認已包含在總費用內，避免重複計算。\n- 確認禮物和交付方式（如有）。\n- 按時間傳提示，遇關閉或不可達時先聯絡本人，勿捏造替代預約。\n`;}
const escapeICS=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');
export function calendarICS(plan:Plan,url:string){const stamp=(n:number)=>new Date(n).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');const rows=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Arcana//Private itinerary//ZH','CALSCALE:GREGORIAN'];plan.stops.forEach((s,i)=>{const at=releaseTime(plan,s);rows.push('BEGIN:VEVENT',`UID:arcana-${plan.trip.date}-${s.poi.id}-${i}`,`DTSTAMP:${stamp(Date.now())}`,`DTSTART:${stamp(at)}`,`DTEND:${stamp(at+60000)}`,`SUMMARY:Arcana 第 ${i+1} 個提示`, `DESCRIPTION:${escapeICS('打開私有行程查看此刻提示。未來站點保持隱藏。 '+url)}`,'BEGIN:VALARM','TRIGGER:PT0M','ACTION:DISPLAY','DESCRIPTION:打開 Arcana 查看提示','END:VALARM','END:VEVENT');});return rows.concat('END:VCALENDAR').map(line=>{let out='',part='';for(const ch of line){if(new TextEncoder().encode(part+ch).length>70){out+=part+'\r\n ';part='';}part+=ch;}return out+part;}).join('\r\n');}
