import {env} from 'cloudflare:workers';
import {validateTrip,questions,type Snapshot} from '../../../lib/tarot/core';
import {createRound,readRound,reveal,lease,release,consume} from '../../../lib/tarot/store';
import {optimize} from '../../../lib/tarot/planner';
import {demoProvider} from '../../../lib/tarot/demo';
import {googleProvider,parseCatalog} from '../../../lib/tarot/google';
export async function POST(req:Request){const url=new URL(req.url);const origin=req.headers.get('origin');if(origin&&origin!==url.origin)return Response.json({error:'來源不符。'},{status:403});if(!req.headers.get('content-type')?.includes('application/json'))return Response.json({error:'需要 JSON。'},{status:415});const cookie=req.headers.get('cookie')?.match(/(?:^|;\s*)arcana_session=([a-f0-9-]{36})(?:;|$)/)?.[1];const session=cookie||crypto.randomUUID();const headers={'Cache-Control':'no-store','Set-Cookie':`arcana_session=${session}; HttpOnly; SameSite=Strict; Path=/; Max-Age=86400${url.protocol==='https:'?'; Secure':''}`};const reply=(data:unknown,status=200)=>Response.json(data,{status,headers});try{const raw=await req.text();if(raw.length>4096)return reply({error:'請求太大。'},413);const body=JSON.parse(raw);if(body.action==='create'){const trip=validateTrip(body.trip);if(trip.mode==='live'&&(!env.GOOGLE_MAPS_API_KEY||!parseCatalog(env.VERIFIED_POI_CATALOG).length))return reply({error:'真實模式需要地圖 API 金鑰及已核實的地點費用資料。'},503);return reply({round:await createRound(session,trip)});}
 if(!['answer','skip','retry'].includes(body.action)||typeof body.id!=='string')return reply({error:'操作無效。'},400);let row=await readRound(body.id,session);const s=JSON.parse(row.snapshot) as Snapshot;if(body.action!=='retry'){if(body.action==='answer'&&!questions.find(q=>q.id===s.questionId)!.options.some(o=>o.id===body.answer))return reply({error:'請選擇有效答案。'},400);const result=await reveal(body.id,session,body.action==='skip'?'skip':body.answer);row=result.row;if(row.status==='void'){if(!result.consumed)return reply({error:'此輪已作廢。請開始新一輪。'},409);return reply({voided:true,round:await createRound(session,s.trip)});}}
 if(row.status!=='passed')return reply({error:'請先完成校準。'},409);if(!await lease(row.id))return reply({error:'同輪行程正在核實，請稍後重試。',passed:true,cards:s.cards.slice(1)},409);
 try{await consume(`plan:${session}:${Math.floor(Date.now()/3600000)}`,30);const provider=s.trip.mode==='demo'?demoProvider:googleProvider(env.GOOGLE_MAPS_API_KEY!,parseCatalog(env.VERIFIED_POI_CATALOG),()=>consume(`provider:${new Date().toISOString().slice(0,10)}`,Math.min(10000,Math.max(1,Number(env.DAILY_PROVIDER_LIMIT)||500))));const plan=await optimize(s,provider);return reply({passed:true,cards:s.cards.slice(1),plan,audit:{snapshot:s,salt:row.salt,commitment:row.commitment}});}catch{return reply({passed:true,cards:s.cards.slice(1),error:'無法完成真實資料核實。可以保留本輪牌重試；不會重新抽牌。'},503);}finally{await release(row.id);}
 }catch(error){return reply({error:error instanceof Error&&/^[\u3000-\u9fff]/.test(error.message)?error.message:'資料處理失敗，請稍後再試。'},400);}}
