import {env} from 'cloudflare:workers';
import {validateTrip,publicRound,VERSION,type Snapshot} from '../../../lib/tarot/core';
import {createRound,readRound,reveal,lease,release,consume,savePlan,savedPlan,latestRound,database,dataAccess,type Row} from '../../../lib/tarot/store';
import {optimize,type Plan} from '../../../lib/tarot/planner';
import {openProvider} from '../../../lib/tarot/open-data';
import {googleProvider,parseCatalog,localISO} from '../../../lib/tarot/google';
import {redacted,organizerMarkdown,calendarICS} from '../../../lib/tarot/surprise';
const PAGES_ORIGIN='https://hosoning.github.io';
function allowedOrigin(origin:string,url:URL){return origin===url.origin||origin===PAGES_ORIGIN}
function responseHeaders(origin:string|null,url:URL,token:string){const headers=new Headers({'Cache-Control':'no-store','Set-Cookie':`arcana_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=7776000${url.protocol==='https:'?'; Secure':''}`});if(origin&&allowedOrigin(origin,url)){headers.set('Access-Control-Allow-Origin',origin);headers.set('Vary','Origin')}return headers}
export async function OPTIONS(req:Request){const url=new URL(req.url);const origin=req.headers.get('origin');if(origin&&!allowedOrigin(origin,url))return new Response(null,{status:403});return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':origin||url.origin,'Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, X-Arcana-Session','Access-Control-Max-Age':'86400','Vary':'Origin'}})}
export async function POST(req:Request){const url=new URL(req.url);const origin=req.headers.get('origin');if(origin&&!allowedOrigin(origin,url))return Response.json({error:'来源不符。'},{status:403});if(!req.headers.get('content-type')?.includes('application/json'))return Response.json({error:'需要 JSON。'},{status:415});const externalSession=req.headers.get('x-arcana-session');if(origin===PAGES_ORIGIN&&(!externalSession||! /^[a-f0-9-]{36}$/i.test(externalSession)))return Response.json({error:'会话无效。'},{status:400});const cookie=req.headers.get('cookie')?.match(/(?:^|;\s*)arcana_session=([a-f0-9-]{36})(?:;|$)/)?.[1];const token=cookie||crypto.randomUUID();const user=req.headers.get('oai-authenticated-user-id');const session=externalSession?'web:'+externalSession:user?'user:'+user:token;const headers=responseHeaders(origin,url,token);const reply=(data:unknown,status=200)=>Response.json(data,{status,headers});
 try{const raw=await req.text();if(raw.length>8192)return reply({error:'请求太大。'},413);const body=JSON.parse(raw);
 if(body.action==='schedules'){const rows=await database().prepare('SELECT r.id,r.snapshot FROM schedules s JOIN rounds r ON r.id=s.round_id WHERE s.session_id=? AND r.expires_at>? ORDER BY s.created_at DESC').bind(session,Date.now()).all<{id:string;snapshot:string}>();return reply({schedules:rows.results.map(r=>({id:r.id,trip:(JSON.parse(r.snapshot) as Snapshot).trip}))});}
 if(body.action==='unschedule'){await database().prepare('DELETE FROM schedules WHERE round_id=? AND session_id=?').bind(String(body.id),session).run();return reply({removed:true});}
 if(body.action==='create'){const trip=validateTrip(body.trip);if(trip.mode!=='live')return reply({error:'已移除虚构行程，请使用真实资料。'},400);const zone=trip.timezone||'America/Vancouver',now=Date.now();if(trip.allDay){const localStart=Date.parse(localISO(trip.date,0,zone));if(localStart<=now){const nowMinute=Math.floor((now-localStart)/60000);trip.start=Math.min(trip.end-60,Math.max(trip.start,nowMinute));}}else if(Date.parse(localISO(trip.date,trip.start,zone))<=now)return reply({error:'出发时间已经过了，请选择之后的日期或时段。'},400);return reply({round:await createRound(session,trip)});}
 let row:Row|null=body.action==='resume'?await latestRound(session):typeof body.id==='string'?await readRound(body.id,session):null;if(!row)return reply(body.action==='resume'?{}:{error:'操作无效。'},body.action==='resume'?200:400);const s=JSON.parse(row.snapshot) as Snapshot;if(s.version!==VERSION)return reply(body.action==='resume'?{}:{error:'这是旧版约会，请重新安排。'},body.action==='resume'?200:409);const current=()=>publicRound(row!.id,s,row!.commitment,row!.expires_at);
 if(body.action==='answer'||body.action==='skip'){if(body.action==='answer'&&!['yes','no'].includes(body.answer))return reply({error:'请回答对／不对。'},400);const result=await reveal(row.id,session,body.action==='skip'?'skip':body.answer);row=result.row;if(row.status==='void'){if(!result.consumed)return reply({error:'此轮已作废，不能再次回答。'},409);return reply({voided:true,voidAudit:{snapshot:s,salt:row.salt,commitment:row.commitment},round:await createRound(session,s.trip)});}}
 if(row.status==='pending')return reply({round:current()});if(row.status!=='passed')return reply({error:'此轮已作废。'},409);
 let saved=await savedPlan(row.id,session);if(!saved){if(!['answer','retry','resume'].includes(body.action))return reply({error:'行程尚未建立。'},409);if(!await lease(row.id))return reply({passed:true,round:current(),error:'同轮行程正在核实，请稍后重试。'},409);try{await consume(`plan:${session}:${Math.floor(Date.now()/3600000)}`,30);const provider=env.GOOGLE_MAPS_API_KEY&&parseCatalog(env.VERIFIED_POI_CATALOG).length?googleProvider(env.GOOGLE_MAPS_API_KEY,parseCatalog(env.VERIFIED_POI_CATALOG),()=>consume('google:'+new Date().toISOString().slice(0,10),200)):openProvider(dataAccess);const plan=await optimize(s,provider);if(!plan.stops.length)return reply({passed:true,round:current(),plan,cards:s.cards.slice(3),audit:{snapshot:s,salt:row.salt,commitment:row.commitment}});await savePlan(row.id,session,plan,row.expires_at);saved=await savedPlan(row.id,session);}catch(error){console.error('planning_failed',error instanceof Error?error.message:'unknown');return reply({passed:true,round:current(),error:error instanceof Error&&/^[\u3000-\u9fff]/.test(error.message)?error.message:'无法完成资料核实。请用同一轮牌重试。'},503);}finally{await release(row.id);}}
 if(!saved)return reply({error:'储存暂时失败。'},503);const plan=JSON.parse(saved.plan) as Plan;
 if(body.action==='schedule'){const expires=Math.max(Date.now()+86400000,Date.parse(plan.trip.date)+30*86400000);await database().batch([database().prepare('INSERT INTO schedules(round_id,session_id,created_at) VALUES(?,?,?) ON CONFLICT(round_id) DO NOTHING').bind(row.id,session,Date.now()),database().prepare('UPDATE rounds SET expires_at=? WHERE id=? AND session_id=?').bind(expires,row.id,session),database().prepare('UPDATE itineraries SET expires_at=? WHERE round_id=? AND session_id=?').bind(expires,row.id,session)]);return reply({scheduled:true});}
 
 if(body.action==='export'){if(body.confirmSpoilers!==true)return reply({error:'请确认这是交给执行方的完整剧透资料。'},400);return reply({text:organizerMarkdown(plan),filename:'arcana-organizer.md'});}
 if(body.action==='calendar')return reply({text:calendarICS(plan,origin===PAGES_ORIGIN?'https://hosoning.github.io/planner':url.origin),filename:'arcana-hints.ics'});
 if(body.action==='revealAll'){if(body.confirmSpoilers!==true)return reply({error:'请确认结束惊喜模式。'},400);await database().prepare('UPDATE itineraries SET revealed=1 WHERE round_id=? AND session_id=?').bind(row.id,session).run();saved.revealed=1;}
 if(body.action==='booking'){if(!['confirmed','unbooked'].includes(body.status)||typeof body.paid!=='boolean')return reply({error:'请填写预约及付款状态。'},400);const original=saved.plan;const stop=plan.stops.find(x=>x.poi.id===body.stopId);if(!stop)return reply({error:'找不到此项目。'},400);stop.poi.booking.status=body.status;stop.poi.booking.paid=body.paid;stop.poi.booking.reference=String(body.reference||'').slice(0,120);const change=await database().prepare('UPDATE itineraries SET plan=? WHERE round_id=? AND session_id=? AND plan=? RETURNING round_id').bind(JSON.stringify(plan),row.id,session,original).first();if(!change)return reply({error:'资料已更新，请重新载入后再操作。'},409);}
 if(body.action==='recordTask'){if(body.confirm!==true||!['booking','payment','gift'].includes(body.kind))return reply({error:'请先确认执行方已完成此事项。'},400);if(body.kind==='gift')plan.gift.handled=true;else{const stop=plan.stops.find(x=>x.poi.id===body.stopId);if(!stop)return reply({error:'事项不存在。'},400);if(body.kind==='booking')stop.poi.booking.status='confirmed';else stop.poi.booking.paid=true;}const changed=await database().prepare('UPDATE itineraries SET plan=? WHERE round_id=? AND session_id=? AND plan=? RETURNING round_id').bind(JSON.stringify(plan),row.id,session,saved.plan).first();if(!changed)return reply({error:'纪录已变更，请重新载入。'},409);}
 if(body.action==='giftDone'){if(!Number.isSafeInteger(body.spent)||body.spent<0||body.spent>plan.gift.reserve)return reply({error:'礼物费用必须在预留上限内。'},400);plan.gift.handled=true;await database().prepare('UPDATE itineraries SET plan=? WHERE round_id=? AND session_id=? AND plan=?').bind(JSON.stringify(plan),row.id,session,saved.plan).run();}
 const surprise=redacted(plan);if(plan.intent.surprise&&!saved.revealed)return reply({passed:true,round:current(),surprise});return reply({passed:true,round:current(),plan,cards:s.cards.slice(3),audit:{snapshot:s,salt:row.salt,commitment:row.commitment}});
 }catch(error){return reply({error:error instanceof Error&&/^[\u3000-\u9fff]/.test(error.message)?error.message:'资料处理失败，请稍后再试。'},400);}}
