import {env} from 'cloudflare:workers';
import {validateTrip,publicRound,VERSION,type Snapshot} from '../../../lib/tarot/core';
import {createRound,readRound,reveal,lease,release,consume,savePlan,savedPlan,latestRound,database,type Row} from '../../../lib/tarot/store';
import {optimize,type Plan} from '../../../lib/tarot/planner';
import {demoProvider} from '../../../lib/tarot/demo';
import {googleProvider,parseCatalog} from '../../../lib/tarot/google';
import {redacted,organizerMarkdown,calendarICS} from '../../../lib/tarot/surprise';
export async function POST(req:Request){const url=new URL(req.url);const origin=req.headers.get('origin');if(origin&&origin!==url.origin)return Response.json({error:'來源不符。'},{status:403});if(!req.headers.get('content-type')?.includes('application/json'))return Response.json({error:'需要 JSON。'},{status:415});const cookie=req.headers.get('cookie')?.match(/(?:^|;\s*)arcana_session=([a-f0-9-]{36})(?:;|$)/)?.[1];const session=cookie||crypto.randomUUID();const headers={'Cache-Control':'no-store','Set-Cookie':`arcana_session=${session}; HttpOnly; SameSite=Strict; Path=/; Max-Age=7776000${url.protocol==='https:'?'; Secure':''}`};const reply=(data:unknown,status=200)=>Response.json(data,{status,headers});
 try{const raw=await req.text();if(raw.length>8192)return reply({error:'請求太大。'},413);const body=JSON.parse(raw);if(body.action==='create'){const trip=validateTrip(body.trip);if(trip.mode==='live'&&(!env.GOOGLE_MAPS_API_KEY||!parseCatalog(env.VERIFIED_POI_CATALOG).length))return reply({error:'真實模式需要地圖 API 金鑰及已核實的地點、地址與預訂資料。'},503);return reply({round:await createRound(session,trip)});}
 let row:Row|null=body.action==='resume'?await latestRound(session):typeof body.id==='string'?await readRound(body.id,session):null;if(!row)return reply(body.action==='resume'?{}:{error:'操作無效。'},body.action==='resume'?200:400);const s=JSON.parse(row.snapshot) as Snapshot;if(s.version!==VERSION)return reply({error:'這是舊版牌陣，請開始新版完整抽取。'},409);const current=()=>publicRound(row!.id,s,row!.commitment,row!.expires_at);
 if(body.action==='answer'||body.action==='skip'){if(body.action==='answer'&&!['yes','no'].includes(body.answer))return reply({error:'請回答對／不對。'},400);const result=await reveal(row.id,session,body.action==='skip'?'skip':body.answer);row=result.row;if(row.status==='void'){if(!result.consumed)return reply({error:'此輪已作廢，不能再次回答。'},409);return reply({voided:true,voidAudit:{snapshot:s,salt:row.salt,commitment:row.commitment},round:await createRound(session,s.trip)});}}
 if(row.status==='pending')return reply({round:current()});if(row.status!=='passed')return reply({error:'此輪已作廢。'},409);
 let saved=await savedPlan(row.id,session);if(!saved){if(!['answer','retry','resume'].includes(body.action))return reply({error:'行程尚未建立。'},409);if(!await lease(row.id))return reply({passed:true,round:current(),error:'同輪行程正在核實，請稍後重試。'},409);try{await consume(`plan:${session}:${Math.floor(Date.now()/3600000)}`,30);const provider=s.trip.mode==='demo'?demoProvider:googleProvider(env.GOOGLE_MAPS_API_KEY!,parseCatalog(env.VERIFIED_POI_CATALOG),()=>consume(`provider:${new Date().toISOString().slice(0,10)}`,Math.min(10000,Math.max(1,Number(env.DAILY_PROVIDER_LIMIT)||500))));const plan=await optimize(s,provider);if(!plan.stops.length)return reply({passed:true,round:current(),plan,cards:s.cards.slice(1),audit:{snapshot:s,salt:row.salt,commitment:row.commitment}});await savePlan(row.id,session,plan,row.expires_at);saved=await savedPlan(row.id,session);}catch{return reply({passed:true,round:current(),error:'無法完成資料核實。可以保留本輪牌重試；不會重新抽牌。'},503);}finally{await release(row.id);}}
 if(!saved)return reply({error:'儲存暫時失敗。'},503);let plan=JSON.parse(saved.plan) as Plan;
 if(body.action==='export'){if(body.confirmSpoilers!==true)return reply({error:'請確認這是交給執行方的完整劇透資料。'},400);return reply({text:organizerMarkdown(plan),filename:'arcana-organizer.md'});}
 if(body.action==='calendar')return reply({text:calendarICS(plan,url.origin),filename:'arcana-hints.ics'});
 if(body.action==='revealAll'){if(body.confirmSpoilers!==true)return reply({error:'請確認結束驚喜模式。'},400);await database().prepare('UPDATE itineraries SET revealed=1 WHERE round_id=? AND session_id=?').bind(row.id,session).run();saved.revealed=1;}
 if(body.action==='booking'){if(!['confirmed','unbooked'].includes(body.status)||typeof body.paid!=='boolean')return reply({error:'請填寫預約及付款狀態。'},400);const original=saved.plan;const stop=plan.stops.find(x=>x.poi.id===body.stopId);if(!stop)return reply({error:'找不到此項目。'},400);stop.poi.booking.status=body.status;stop.poi.booking.paid=body.paid;stop.poi.booking.reference=String(body.reference||'').slice(0,120);const change=await database().prepare('UPDATE itineraries SET plan=? WHERE round_id=? AND session_id=? AND plan=? RETURNING round_id').bind(JSON.stringify(plan),row.id,session,original).first();if(!change)return reply({error:'資料已更新，請重新載入後再操作。'},409);}
 if(body.action==='recordTask'){if(body.confirm!==true||!['booking','payment','gift'].includes(body.kind))return reply({error:'請先確認執行方已完成此事項。'},400);if(body.kind==='gift')plan.gift.handled=true;else{const stop=plan.stops.find(x=>x.poi.id===body.stopId);if(!stop)return reply({error:'事項不存在。'},400);if(body.kind==='booking')stop.poi.booking.status='confirmed';else stop.poi.booking.paid=true;}const changed=await database().prepare('UPDATE itineraries SET plan=? WHERE round_id=? AND session_id=? AND plan=? RETURNING round_id').bind(JSON.stringify(plan),row.id,session,saved.plan).first();if(!changed)return reply({error:'紀錄已變更，請重新載入。'},409);}
 if(body.action==='giftDone'){if(!Number.isSafeInteger(body.spent)||body.spent<0||body.spent>plan.gift.reserve)return reply({error:'禮物費用必須在預留上限內。'},400);plan.gift.handled=true;await database().prepare('UPDATE itineraries SET plan=? WHERE round_id=? AND session_id=? AND plan=?').bind(JSON.stringify(plan),row.id,session,saved.plan).run();}
 const surprise=redacted(plan);if(plan.intent.surprise&&!saved.revealed)return reply({passed:true,round:current(),surprise});return reply({passed:true,round:current(),plan,cards:s.cards.slice(1),audit:{snapshot:s,salt:row.salt,commitment:row.commitment}});
 }catch(error){return reply({error:error instanceof Error&&/^[\u3000-\u9fff]/.test(error.message)?error.message:'資料處理失敗，請稍後再試。'},400);}}
